language: cpp
os:
- linux
env:
  global:
  - OMP_NUM_THREADS=4
  - C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/include/libtcod
  - CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/include/libtcod
  - LD_LIBRARY_PATH=/usr/local/lib
  - secure: "${COVERITY_SCAN_TOKEN}"
before_script:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++
  g++ /usr/bin/g++-8
- chmod u+x install_deps_linux.sh
- "./install_deps_linux.sh"
before_install: 
addons:
  coverity_scan:
    project:
      name: y2s82/goblin_camp
      description: goblin camp loves coverity scan. please work.
    notification_email: y2s1982@gmail.com
    build_command_prepend: cmake .
    build_command: make
    branch_pattern: coverity_scan
jobs:
  include:
  - stage: deploy
    compiler:
    - gcc
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntu-toolchain-r/test
        packages:
        - libboost1.54-all-dev
        - libegl1-mesa-dev libgles2-mesa-dev
        - libsdl1.2-dev libsdl-image1.2-dev
        - libpng++-dev
        - zlib1g-dev
        - libgl1-mesa-glx
        - libglew-dev
        - freeglut3-dev
        - g++-8 gcc-8
    script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then cmake .; make; sudo make install;cmake
      .; sudo make install; tar -cf release.tar pkg; fi
deploy:
  provider: releases
  api_key:
    secure: L6R4GTD9qwJQoQCu35wVuqvF0n+tWNI8QYYoPvbwdtevac5EXkZDqaRHmvYQiq8wYISx0j4uj+XZTq7ot81xkT4w4a6ED58HfFOANcjMrgrPrl3xFDZYBgpKXgYTiB9fIV23You90vhP1FjNwg9kKZRm1dOUSc1VRLaHy3Ypritip6G3agT6Nw0jbptv9XVb0r2YoT16IUJEfBUljHH16S145bcC66feVYJUtdNyb7da2ArMoV4dtUGzl8nMjNiC8PlVhS/YQWAjWTBa4woREMG+FRueAt/bdceF12lSn1myGUtha1ytQIzh9Y2tNb3cMk4XKZyCwAtqu2njL7Sgx2s0rH8zme1c0NHxl63ViMpgqw6QroqR97yXn2aZcXDkPVGeJMqSqgCwPP34ZSo2IaxqHocl5ariZ0EYblp9jZeCMfth8KXM78QMFft2/TzoUyaeW9v39kwkELk+kj9XrFffxXVlj74l9QdTeCiOo4WIdnVdTh3Xse4gprB5wHGvRoH+ecgypF44y1uNxJ4pqlnUiPir5jx4E4+sshKo6axi+Rng93ucmWMXwV2qHeUJdyQd5AogNIu3UqhmIZx+NfJ0yd0AjqPcM8YKECT1NlCsQIZMoQuITdVMnGWTfdajIUp8lgLWuGdB1kOPSTF1IFbArqRQtYf4J+m640VoJBE=
  file: release.tar
  skip_cleanup: true
  on:
    repo: y2s82/goblin_camp
    branch: working-build
    tags:true
