language: cpp
env: 
    global:
        - OMP_NUM_THREADS=4
        - C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/include/libtcod
        - CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/include/libtcod
        - LD_LIBRARY_PATH=/usr/local/lib
          # COVERITY_SCAN_TOKEN, specific to this project
        - secure: "negLaugK/dTjOyNLxeP/bLRsVpeP+ShpSw6Y8sLYtajLIEWMxwpcACgWzX5jKQEnac/qpXbv3nPs1tUTXkDYmbfi+uz5oeSMott/8Ua6RH0tMAYP7CgiOF/VHMHES5vQUtcTyUpbyuNM99SBPh2v4cR5TZ30BseIvsx5z7jispKlcl9puwYI9tHoMsstbG17CSq8UCZg2alSjd8jBDCGeHMCi3eQm4OJ6/7j0lfRpMKishdVPMNiMPkH8m+fn4JLBh2y0nJt8fpR95qVNmJV0tkaTOOkOlCXsl24Xnw+UfB2lOFglmKdE9cq8lVNHdhI1EYnyVAizYeY5DCngOyOUnshsPq6KzI5Nkw6euRULRONiep+Bqq2Xn4otWEwQORUnGAOLlV2+IzNUUolGpw9H0iMFdPV/6N8ia4x94oTAe+eUjmfVz2OmNIMLlVqlGxp3SlDFrQGwAy0j3M+V5Eb7ztzqDXvIzgMVyMtL3Pq5XMrCyYZ7268TQK0a+iVKuPJzpPKuxVlTLUcUfDhGDGk9gw5boEXkxF5HsR9gJ4LQ9zIuno099mPZ1y3qpYfylzxFfQL8rrkuUPlp+jcMHZtsZkBWwxUdmLfjeJGjqNas6+n8/yv7iBQ7dP/ldn2GInES+2p0vvCzBuIMdkTFQ0e0k89bWNG5hzrbG9807ae4dw="
before_install:
    - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    - sudo apt-get update
    - sudo apt-get install -y libboost1.54-all-dev
    - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
    - sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev
    - sudo apt-get install -y autoconf automake libtool libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libesd0-dev libdbus-1-dev libudev-dev libgles1-mesa-dev
    - sudo apt-get install -y libpng++-dev
    - sudo apt-get install -y zlib1g-dev
    - sudo apt-get install -y libgl1-mesa-glx
    - sudo apt-get install -y libglew-dev
    - sudo apt-get install -y freeglut3-dev
    - sudo apt-get install -y scons
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install -y g++-5 gcc-5
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5 
before_script:
    - curl -o sdl.tar.gz http://hg.libsdl.org/SDL/archive/007dfe83abf8.tar.gz
    - tar -xf sdl.tar.gz
    - cd SDL-007dfe83abf8/
    - mkdir -p build
    - cd build
    - ../configure
    - make
    - sudo make install
    - cd ../..
    - wget https://github.com/libtcod/libtcod/archive/1.9.0.zip -O libtcod-1.9.0.zip
    - unzip libtcod-1.9.0.zip
    - cd libtcod-1.9.0/build/autotools
    - autoreconf -i
    - ./configure CFLAGS='-O2'
    - make
    - sudo make install
    - cd ../../..
addons:
    coverity_scan:
        project:
            name: "y2s82/goblin_camp"
            description: "Goblin Camp Stone Soup, a Dwarf Fortress Clone"
        notification_email: y2s1982@gmail.com
        build_command_prepend: "cmake ."
        build_command: "make"
        branch_pattern: coverity_scan
jobs:
    include:
        - stage: deploy
          compiler:
              - gcc
          script:
              - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then cmake .;make; fi
